/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package espeon;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class EspeonTest {
    @Test void appHasAGreeting() {
        Espeon classUnderTest = new Espeon();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
