/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    implementation("io.netty:netty-all:4.1.78.Final")
    implementation("com.google.code.gson:gson:2.9.0")
    implementation("org.javassist:javassist:3.29.0-GA")
    implementation("org.reflections:reflections:0.10.2")
    implementation("org.slf4j:slf4j-api:latest.release")
    implementation("org.slf4j:slf4j-simple:latest.release")

    // implementation("org.mongodb:mongodb-driver-reactivestreams:4.6.0")
    implementation("org.mongodb:mongodb-driver-sync:4.6.1")
    implementation("redis.clients:jedis:4.2.0")

    implementation(files("../../../../GitPiranha/r and d/Commons WS/Teal Net/Teal Net.jar"))   
    implementation(files("../../../../GitPiranha/r and d/Commons WS/TealWaters/tealwaters.jar"))   
    implementation(files("../../../../GitPiranha/r and d/annotationprocessor.jar"))   
    
    implementation("io.github.spair:imgui-java-app:1.86.4")
}

application {
    // Define the main class for the application.
    mainClass.set("espeon.Espeon")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
