/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package espeon;

import com.souchy.randd.commons.tealwaters.logging.Log;
import com.souchy.randd.commons.tealwaters.logging.Logging;

import espeon.emerald.Emerald;

public class Espeon {

    public static EspeonServer core;

    public static void main(String[] args) throws Exception {
        Emerald.init();

		Log.LogImportance.filter = Integer.parseInt(args[0]);
		Logging.registerLogModule(Espeon.class);
        int port = Integer.parseInt(args[1]);
        boolean ssl = Boolean.parseBoolean(args[2]);
        boolean mock = Boolean.parseBoolean(args[3]);
        new FightMock();

        core = new EspeonServer(port, ssl);
        core.block();
    }

}
