/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    
  id("org.openjfx.javafxplugin") version "0.0.10" apply true
}

repositories {
    // Use Maven Central for resolving dependencies.
    // mavenCentral()
    
    mavenLocal()
    mavenCentral()
    google()
    gradlePluginPortal()
    maven(url="https://oss.sonatype.org/content/repositories/snapshots/")
    maven(url="https://oss.sonatype.org/content/repositories/releases/")
    maven(url="https://jitpack.io")
}


dependencies {
    implementation(project(":Espeon"))

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")
    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
    
    // ImGui    
    implementation("io.github.spair:imgui-java-app:1.86.4")

    // GDX
    implementation("com.badlogicgames.gdx:gdx-backend-lwjgl3:1.11.0")
    implementation("com.badlogicgames.gdx:gdx-platform:1.11.0:natives-desktop")
    implementation("com.badlogicgames.gdx:gdx:1.11.0")
        
}

javafx {
    version = "17.0.1"
    modules("javafx.controls", "javafx.fxml")
}

application {
    // Define the main class for the application.
    mainClass.set("pachinko.Pachinko")
    // mainClass.set("pachinko.PachinkoFX")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
