/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pachinko;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Pachinko classUnderTest = new Pachinko();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
