/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pachinko;

import espeon.emerald.Amber;
import espeon.emerald.Red;

public class Pachinko {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Pachinko().getGreeting());

        Amber.spellModel.setActionId(1, "hi");
        var a = Amber.spellModel.getActionId(1);
        System.out.println("action a : " + a);
    }
}
