/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pachinko;

// import espeon.emerald.Red;

public class Pachinko {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Pachinko().getGreeting());

        // Red.jedis.get("");
    }
}
