/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pachinko;

import espeon.emerald.Red;
import espeon.emerald.amber.Amber;

public class Pachinko {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Pachinko().getGreeting());

        Amber.spells.setActionId("1", "hi");
        var a = Amber.spells.getActionId("1");
        System.out.println("action a : " + a);
    }
}
