# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "Souchy-patch-1" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual build'  

defaults:
  run:
    working-directory: './projects/web/Spark/'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build -c Release -o 'publish/'
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: 'Spark'
        path: '/home/runner/work/Celebi/Celebi/projects/web/Spark/publish/'      
    - run: ls
    
  deployment:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    #steps:
      #- name: deploy
      #/home/souchy/release/celebi/spark
    steps:
      #- name: Test connectivity
      #  run: curl -v telnet://${{ secrets.FTP_SERVER }}:22
        
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: 'Spark'
          
      - name: FTP-Deploy-Action test SamKirkLand
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWD }}
          port: 22
          local-dir: './*' # '/home/runner/work/Celebi/Celebi/'
          server-dir: ${{ secrets.SPARK_PATH }}
      #- run: ls
      #- name: Extract some files
        #run: 7z x 'Spark.zip'
      #- uses: montudor/action-zip@v1
      #  with:
      #    args: unzip -qq 'Spark' -d 'sparkz'
      - name: SFTP Deploy to DeathShadows server
        # You may pin to the exact commit or the version.
        # uses: wlixcc/SFTP-Deploy-Action@da88a4dbe95286266bbac3c0b2b8284048d20c8f
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          # username
          username: ${{ secrets.FTP_USERNAME }}
          # your sftp server
          server: ${{ secrets.FTP_SERVER }}
          # your sftp server port, default to 22
          port: 22 #${{ secrets.FTP_PORT }} # default is 22
          # you can copy private_key from your *.pem file, keep format
          #ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # will put all file under this path
          local_path: '/home/runner/work/Celebi/Celebi/' # default is ./*      # example has './static/*'
          # files will copy to under remote_path
          remote_path: ${{ secrets.SPARK_PATH }} 
          # connection via sftp protocol only
          sftp_only: true # optional
          # sftp args
          #sftpArgs: # optional
          # This operation will delete all files in the remote path before upload. Please be careful set this to true
          #delete_remote_files: # optional
          # SSH passsword，If a password is set, the secret key pair is ignored
          password: ${{ secrets.FTP_PASSWD }}  # optional
      #- name: Deploy to DeathShadows server
      #  id: deploy-to-webapp
      #  uses: azure/webapps-deploy@v2
      #  with:
      #    app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #    package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
