# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "Souchy-patch-1" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual build'  

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: ls
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --verbosity normal
    
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './projects/web/Spark/'
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build -c Release -o 'publish/'
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: 'Spark'
        path: '/home/runner/work/Celebi/Celebi/projects/web/Spark/publish/'      
    - run: ls
        
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: 'Spark'
      - name: Deploy to DeathShadows server
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          #password: ${{ secrets.FTP_PASSWD }}
          localPath: '/home/runner/work/Celebi/Celebi/'
          remotePath: ${{ secrets.SPARK_PATH }} 
          #/home/souchy/release/celebi/spark
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        
      #- run: ls
      #- name: Extract some files
        #run: 7z x 'Spark.zip'
      #- uses: montudor/action-zip@v1
      #  with:
      #    args: unzip -qq 'Spark' -d 'sparkz'
      
