# This workflow will run all tests on pull requests

name: PR Tests

on:
  pull_request:
    branches: [ "master", "bug/workflow-tests" ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual build'

jobs:
  test:
    name: unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './projects/tests/EeveeUnitTests/'
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '/home/runner/work/Celebi/Celebi/projects/web/Spark/appsettings.json'
      env:
        MongoSettings.ConnectionString: ${{ secrets.MongoSettings__ConnectionString}}
        MongoSettings.Federation: ${{ secrets.MongoSettings__Federation }}
        MongoSettings.ModelsDB: ${{ secrets.MongoSettings__ModelsDB }}
        MongoSettings.FightsDB: ${{ secrets.MongoSettings__FightsDB }}
        MongoSettings.MetaDB: ${{ secrets.MongoSettings__MetaDB }}
        MongoSettings.I18NDB: ${{ secrets.MongoSettings__I18NDB }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Eevee Tests           # Name of the check run which will be created
        path: test-results.trx      # Path to test results
        reporter: dotnet-trx        # Format of test results